config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get '/signup', to: 'users#new'
  resources :users do
    resources :todos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  has_secure_password
  validates :password, length:{minimum: 6}, presence: true, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = params[:user_id]
    @todo.completed = false
    if @todo.save
      redirect_to user_path(@todo.user_id)
    else
      render 'todos/new', status: :unprocessable_entity
    end
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update_attribute(:completed, !@todo.completed)
    redirect_to user_path(params[:user_id])
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to user_path(params[:user_id])
  end

  private
    def todo_params
      params.require(:todo).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user_name = User.find(params[:id]).name
    @todos = Todo.where(user_id: params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to the Todo App!'
      redirect_to @user
      # redirect_to user_url(@user)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
  end

  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = '')
    base_title = 'Todo App'
    if title.blank?
      base_title
    else
      "#{title} | #{base_title}"
    end
  end
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<div class="codespaces">
  <header class="codespaces-header">
    <img class="codespaces-logo"
         src="railstutorial.png"
         alt="Railsチュートリアル" />
    <p>
      Codespaces
      <span class="heart">♥️</span>
      Railsチュートリアル
    </p>
    <p class="small">
      🎓✨<br>
      ロゴ画像が表示されたらセットアップ完了です!
    </p>
  </header>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <%= link_to 'Todo App project', 'https://github.com/dmk2E/todo-app' %> By <%= link_to 'dmk2E', 'https://github.com/dmk2E' %>
  </small>
  <nav>
    <ul>
      <li></li>
      <li></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Todo App', root_path, id: 'TITLE' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Sign up",   signup_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/index.html.erb
<div class='center jumbotron'>
  <h1>Welcome to the Todo App</h1>

  <h2>
    This is the home page for the Todo App
  </h2>
  <%= image_tag('img_home.png',width: '500px' ,alt: 'Home page image') %>
</div>
<div class="tech-stack">
  <%= link_to image_tag('rails.svg', alt:'Rails logo', width:'200'), 'https://rubyonrails.org/' %>
</div>

app/views/todos/new.html.erb
<%= provide(:title, 'New todo') %>
<h1>New todo</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model:[@user, @todo]) do |f| %>
      <%= render 'shared/error_messages', object: @todo %>

      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control' %>

      <%= f.submit 'Create new todo', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model:@user) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, 'confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit 'Create my account', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'My page') %>
<h1><%= @user_name %>'s todos</h1>
<div class="flex-row">
  <table>
    <% @todos.each do |todo| %>
      <% class_name = '' %>
      <% if todo.completed %>
        <% class_name = 'completed' %>
        <% btn_content = 'reset' %>
      <% else %>
        <% btn_content = 'completed' %>
      <% end %>
      <tr>
        <td>
          ・
        </td>
        <td class="<%= class_name %>">
          " <%= todo.name %>"
        </td>
        <td>
          -
        </td>
        <td class="center">
          <%= 
            link_to btn_content, 
            user_todo_path(todo.user_id, todo.id), data: {turbo_method: 'patch'}, 
                                                   class:'btn btn-lg btn-success margin-side'
          %>
        </td>
        <td>
          <%= 
            link_to 'delete', user_todo_path(todo.user_id, todo.id), 
                                data:{turbo_method: 'delete', 
                                      turbo_confirm: 'Are you sure?'}, 
                                class:'btn btn-lg btn-danger margin-side'
          %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'New', new_user_todo_path(params[:id]), class: "btn btn-lg btn-primary" %>
</div>